timeout: 0
serial: yes
serial_baudrate: 115200
graphics: no
verbose: yes

/Alpine Custom Initramfs
    protocol: linux
    path: boot():/vmlinuz-virt
    module_path: boot():/alpine-initramfs.img
    kernel_cmdline: console=ttyS0,115200 rdinit=/init loglevel=7
    textmode: yes
